// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAds8q2-fEnJ-E_EJJBcxR37OK_ET1g97M',
    appId: '1:523498240923:web:cc1a15211cd81fc9bebf3e',
    messagingSenderId: '523498240923',
    projectId: 'ems-system-92c4e',
    authDomain: 'ems-system-92c4e.firebaseapp.com',
    storageBucket: 'ems-system-92c4e.firebasestorage.app',
    measurementId: 'G-XJDHNDRD0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCmZeFS69nTQkYz72bpzwtWtjF2F_p-7s',
    appId: '1:523498240923:android:9b3884cf26099e12bebf3e',
    messagingSenderId: '523498240923',
    projectId: 'ems-system-92c4e',
    storageBucket: 'ems-system-92c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-REOP-4AciFjQfwRSqgUWnWI6Gu1bkdY',
    appId: '1:523498240923:ios:6588ad0b43acee8abebf3e',
    messagingSenderId: '523498240923',
    projectId: 'ems-system-92c4e',
    storageBucket: 'ems-system-92c4e.firebasestorage.app',
    iosBundleId: 'com.example.eventmangment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAds8q2-fEnJ-E_EJJBcxR37OK_ET1g97M',
    appId: '1:523498240923:web:b281ea3e4be4cf9ebebf3e',
    messagingSenderId: '523498240923',
    projectId: 'ems-system-92c4e',
    authDomain: 'ems-system-92c4e.firebaseapp.com',
    storageBucket: 'ems-system-92c4e.firebasestorage.app',
    measurementId: 'G-13TRWCNW32',
  );
}
